# config.toml
[cosmic-ray]
module-path = "./largefilehash/src"
python-version = ""
timeout = 10
exclude-modules = []
test-command = "python -m largefilehash.tests._run_all"
execution-engine.name = "local"

[cosmic-ray.cloning]
method = 'copy'
commands = []