# config.toml
[cosmic-ray]
module-path = "./largefilehash"
python-version = ""
timeout = 10
exclude-modules = []
test-command = "python -m unittest discover tests"
execution-engine.name = "local"

[cosmic-ray.cloning]
method = 'copy'
commands = []